version: '3'

services:
  my_api:
    build: .
    ports:
      - "8000:8000"
    expose:
      - 8000
    command: bash -c "python main.py"
    environment:
      CACHE: "redis://redis:6379/0"
    depends_on:
      - my_db
      - redis

  my_db:
    image: postgres:15.1-alpine
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: "${PASSWORD}"
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data/

  redis:
    image: redis:latest
    command: redis-server
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data


  adminer:
    image: adminer
    restart: always
    ports:
      - '8888:8080'

volumes:
  db_data:
  redis_data: