version: '3'

services:
  my_api:
    build: .
    ports:
      - "8000:8000"
    expose:
      - 8000
    command: bash -c "python -m pytest tests/menu_test.py &&
      python -m pytest tests/submenu_test.py &&
      python -m pytest tests/dish_test.py &&      
      python -m pytest tests/count_test.py"
    depends_on:
      - my_db

  my_db:
    image: postgres:15.1-alpine
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: "${PASSWORD}"
    ports:
      - "5432:5432"
    volumes:
      - test_db_data:/var/lib/postgresql/data/

volumes:
  test_db_data: