version: '3'

services:
  my_api:
    build: .
    ports:
      - "8000:8000"
    expose:
      - 8000
    environment:
      CACHE: "redis://redis:6379/0"
    command: bash -c "python -m pytest tests/menu_test.py &&
      python -m pytest tests/submenu_test.py &&
      python -m pytest tests/dish_test.py &&
      python -m pytest tests/count_test.py"
    depends_on:
      my_db:
        condition: service_healthy
      redis:
        condition: service_healthy

  my_db:
    image: postgres:15.1-alpine
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: "${PASSWORD}"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 30s
      retries: 5
    volumes:
      - test_db_data:/var/lib/postgresql/data/

  redis:
    image: redis:latest
    command: redis-server
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - redis_data:/data

volumes:
  test_db_data:
  redis_data:
